[general]
enable_bucket = true
bucket_no_upscale = true
min_bucket_reso = 384
max_bucket_reso = 1536
bucket_reso_steps = 64

[[datasets]]
resolution = [768, 768]
batch_size = 1
caption_extension = ".txt"
fad_p_min = 0.35
fad_p_max = 1
fad_alpha = 10
fad_c = 0.5
fad_curriculum_start = 0.1
fad_curriculum_end = 0.5
fad_curriculum_beta = 3
fad_step_start = 0
fad_step_end = 1
folder_shift_curriculum = true

  [[datasets.subsets]]
  image_dir = ""
  num_repeats = 1
  keep_tokens = 1
  class_tokens = ""
  keep_tags = ""
  flip_aug = false
  caption_prefix = ""
  caption_dropout_rate = 0
  caption_tag_dropout_rate = 0
  caption_dropout_every_n_epochs = 0
  shuffle_caption = true
  enable_wildcard = true
  enable_fad = true
  fad_curriculum = true
  fad_timestep = false
  alpha_mask = true
  folder_shift = "global"
  is_reg = false
