[general]
enable_bucket = true
bucket_no_upscale = true
min_bucket_reso = 384
max_bucket_reso = 1536
bucket_reso_steps = 64

[[datasets]]
resolution = [768, 768]
batch_size = 1
caption_extension = ".txt"
fad_p_min = 0.35
fad_p_max = 1
fad_alpha = 10
fad_c = 0.5
fad_curriculum_start = 0.1
fad_curriculum_end = 1
fad_curriculum_beta = 3
fad_step_start = 0
fad_step_end = 1
folder_shift_curriculum = true

  [[datasets.subsets]]
  image_dir = ""
  num_repeats = 1
  keep_tokens = 1
  class_tokens = ""
  keep_tags = "1girl, 1boy, 1other, .*girls, .*boys, .*others, .*out_of_frame, cropped_.*, disembodied_.*, letterboxed, pillarboxed, .*_border, round_image, circle_cut, split_screen, variations, comparison, .*koma, .*comic, column_lineup, nengajou, .*chart, zoom_layer, .*_inset, .*_background, .*watermark, copyright_notice, signature, qr_code, artist_logo, pixiv_logo, twitter_logo, instagram_logo, .*_logo, .*_name, pixiv_id, .*_username, window_(computing), fake_screenshot, fake_phone_screenshot, battery_indicator, timestamp, cursor, art_program_in_frame, d-pad, gameplay_mechanics, ranguage, .*text, profanity, .*speech_bubble, thought_bubble, lyrics, page_number, subtitled, .*censor.*, chromatic_aberration, film_grain, blending, .*blur.*, .*_profile, .*cover, multiple_.*, ranguage, .*_(medium), monochrome, greyscale, sketch"
  flip_aug = false
  caption_prefix = ""
  caption_dropout_rate = 0.1
  caption_tag_dropout_rate = 0
  caption_dropout_every_n_epochs = 0
  shuffle_caption = true
  enable_wildcard = true
  enable_fad = true
  fad_curriculum = true
  fad_timestep = true
  alpha_mask = true
  folder_shift = "global"
