venv_path = ""
jobs_dir = ""

[openrouter]
api_url = "https://openrouter.ai/api/v1"
api_key = ""
model = "perceptron/perceptron-mk1"

[model_paths]
# Anima Paths
dit_path = ""
qwen3_path = ""
vae_path = ""

# Krea 2 Paths
krea2_dit_path = ""
krea2_text_encoder_path = ""
krea2_vae_path = ""

[ui]
background = ""
background_position = "50% 50%"
dim_level = 0
brightness_level = 100
blur_level = 0
text_shadow_size = 0
theme = "github-dark"

